### ISSUE TITLE
generate_jitter() question

### ISSUE THREAD

**Issue by cbattista** [jchen53/Symbolic_NonSymbolic_Representation#3]
what does this code do?

```
for time in time_list:
    if time>=min_duration and time<=max_duration:
        counter+=1
        jitter.append(time)
    if counter==num_trials:
        break
```

**Comment by jchen31995** [comment]
The first jitter ranges from 1.5-5.5 seconds and the fixation jitter ranges from 1.9-8.4 seconds. It just makes sure that jitter is within that range since initial list1 generates from 1.0-8.9 sec. generate_jitter() should be able to create a list of jitters for any range between 1.0 and 8.9 sec
